routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('roles', App\Http\Controllers\RoleController::class);
    Route::resource('users', App\Http\Controllers\UserController::class);
    Route::resource('pages', App\Http\Controllers\PageBuilderController::class);
    Route::get('admin/settings', 'App\Http\Controllers\SettingsController@edit')->name('settings.edit');
    Route::post('admin/settings', 'App\Http\Controllers\SettingsController@update')->name('settings.update');
    Route::get('pages.setting', 'App\Http\Controllers\PageBuilderController@setting')->name('pages.setting');
    Route::post('admin/pagebuilder', 'App\Http\Controllers\PageBuilderController@storePage');
    Route::patch('admin/pagebuilder', 'App\Http\Controllers\PageBuilderController@storePage');
    Route::any('preview/{uri}', [
        'uses' => 'App\Http\Controllers\RouteController@previewPage',
        'as' => 'page',
    ])->where('uri', '.*');
});

// TODO: temporary workaround to get the public theme file
Route::get('themes/demo/{prefix}/{name}.{extension}', 'App\Http\Controllers\RouteController@getThemePublicFile')
    ->where('name', '[a-zA-Z0-9-]+')
    ->where('prefix', '[js, css]+')
    ->where('extension', '[js, css]+');

Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\LanguageController@switchLang']);
Route::get('currentLang', ['as' => 'lang.get', 'uses' => 'App\Http\Controllers\LanguageController@getCurrentLang']);

Route::any('{uri}', [
    'uses' => 'App\Http\Controllers\RouteController@indexHtml',
    'as' => 'page',
])->where('uri', '.*');

resources/views/pages/create.blade.php
@extends('layouts.app')
@section('title')
    Create Page
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">New Page</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('pages.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'pages.store']) !!}
                                    <div class="row">
                                        @include('pages.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Page
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">Edit Page</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('pages.index') }}"  class="btn btn-primary">Back</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($page, ['route' => ['pages.update', $page->get('id')], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('pages.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/pages/fields.blade.php
<?php
$pageUrlParam = '';
if (isset($page)) {
    $pageUrlParam = '&page=' . phpb_e($page->getId());
    $pageTranslations = $page ? $page->getTranslations() : [];
}

?>

<div class="form-group col-sm-6 col-md-4">
    {!! Form::label('name', 'Name:') !!}
    @if(str_contains(url()->full(),'pages.setting?id'))
        {!! Form::text('name', $page->getName(), ['class' => 'form-control']) !!}
    @else
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    @endif
</div>

<div class="form-group col-sm-6 col-md-4">
    {!! Form::label('url', 'URL:') !!}
    @if(str_contains(url()->full(),'pages.setting?id'))
        {!! Form::text('url', $page->getRoute(), ['class' => 'form-control']) !!}
    @else
        {!! Form::text('url', null, ['class' => 'form-control']) !!}
    @endif
</div>

<div class="form-group col-sm-12">
    <?php
    foreach (phpb_active_languages() as $languageCode => $languageTranslation):
    ?>
    <h5 class="pt-2 border-bottom border-top"><?= phpb_trans('languages.' . $languageCode) ?></h5>
    <div class="pt-2 pl-3 pr-3">

    </div>

    <div class="row">
        <div class="col-sm-12">
            <h6 class="text-center">Web</h6>
        </div>

        <div class="form-group required col-sm-12">
            <label for="page-title"><?= phpb_trans('website-manager.page-title') ?></label>
            <input type="text" class="form-control" id="page-title" name="title[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['title'] ?? '') ?>" required>
        </div>
        <div class="form-group col-sm-12">
            <label for="page-description">{{ __('pagebuilder.description') }}</label>
            <input type="text" class="form-control" id="page-description" name="description[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['description'] ?? '') ?>">
        </div>

        <hr>

        <div class="col-sm-12">
            <h6 class="text-center">Twitter</h6>
        </div>

        <div class="form-group col-sm-6 col-md-4">
            <label for="page-twitter_creator">{{ __('pagebuilder.twitter_creator') }}</label>
            <input type="text" class="form-control" id="page-twitter_creator" name="twitter_creator[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['twitter_creator'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="page-twitter_card">{{ __('pagebuilder.twitter_card') }}</label>
            <input type="text" class="form-control" id="page-twitter_card" name="twitter_card[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['twitter_card'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="page-twitter_site">{{ __('pagebuilder.twitter_site') }}</label>
            <input type="text" class="form-control" id="page-twitter_site" name="twitter_site[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['twitter_site'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="page-twitter_title">{{ __('pagebuilder.twitter_title') }}</label>
            <input type="text" class="form-control" id="page-twitter_title" name="twitter_title[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['twitter_title'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="page-twitter_image">{{ __('pagebuilder.twitter_image') }}</label>
            <input type="text" class="form-control" id="page-twitter_image" name="twitter_image[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['twitter_image'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="page-twitter_image_alt">{{ __('pagebuilder.twitter_image_alt') }}</label>
            <input type="text" class="form-control" id="page-twitter_image_alt" name="twitter_image_alt[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['twitter_image_alt'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-12">
            <label for="page-twitter_description">{{ __('pagebuilder.twitter_description') }}</label>
            <input type="text" class="form-control" id="page-twitter_description" name="twitter_description[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['twitter_description'] ?? '') ?>">
        </div>

        <div class="col-sm-12">
            <h6 class="text-center">Facebook</h6>
        </div>

        <div class="form-group col-sm-6 col-md-4">
            <label for="page-og_title">{{ __('pagebuilder.og_title') }}</label>
            <input type="text" class="form-control" id="page-og_title" name="og_title[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['og_title'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="page-og_type">{{ __('pagebuilder.og_type') }}</label>
            <input type="text" class="form-control" id="page-og_type" name="og_type[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['og_type'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="page-og_url">{{ __('pagebuilder.og_url') }}</label>
            <input type="text" class="form-control" id="page-og_url" name="og_url[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['og_url'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="page-og_image">{{ __('pagebuilder.og_image') }}</label>
            <input type="text" class="form-control" id="page-og_image" name="og_image[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['og_image'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="page-og_locale">{{ __('pagebuilder.og_locale') }}</label>
            <input type="text" class="form-control" id="page-og_locale" name="og_locale[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['og_locale'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="page-fb_app_id">{{ __('pagebuilder.fb_app_id') }}</label>
            <input type="text" class="form-control" id="page-fb_app_id" name="fb_app_id[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['fb_app_id'] ?? '') ?>">
        </div>
        <div class="form-group col-sm-12">
            <label for="page-og_description">{{ __('pagebuilder.og_description') }}</label>
            <input type="text" class="form-control" id="page-og_description" name="og_description[<?= phpb_e($languageCode) ?>]"
                   value="<?= phpb_e($pageTranslations[$languageCode]['og_description'] ?? '') ?>">
        </div>
    </div>


    <?php
    endforeach;
    ?>
</div>

@can('update-page-status')
    <div class="form-group col-sm-4">
        {!! Form::label('status', 'Status:') !!}
        {!! Form::select('status', $status, null, ['class' => 'form-control select2']) !!}
    </div>
@endcan

@can('update-published-date')
    <div class="form-group col-sm-4">
        {!! Form::label('published_at', 'Published At:') !!}
        @if (!str_contains(url()->full(),'pages.setting?id'))
            <input type="datetime-local" class="form-control" value="{{date('Y-m-d\TH:i')}}" id="published_at"
                   name="published_at">
        @else
            <input type="datetime-local" class="form-control"
                   value="{{date('Y-m-d\TH:i',strtotime($page->published_at))}}" id="published_at" name="published_at">
        @endif
    </div>
@endcan

@can('update-unpublished-date')
    <div class="form-group col-sm-4">
        {!! Form::label('unpublished_at', 'Unpublished At:') !!}
        @if (!str_contains(url()->full(),'pages.setting?id'))
            <input type="datetime-local" class="form-control"
                   value="{{date('Y-m-d\TH:i',strtotime('+1 month',strtotime(date('Y-m-d\TH:i'))))}}"
                   id="unpublished_at"
                   name="unpublished_at">
        @else
            <input type="datetime-local" class="form-control"
                   value="{{date('Y-m-d\TH:i',strtotime($page->unpublished_at))}}" id="unpublished_at"
                   name="unpublished_at">
        @endif
    </div>
@endcan

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('pages.index') }}" class="btn btn-light">Cancel</a>
</div>

resources/views/pages/index.blade.php
@extends('layouts.app')
@section('title')
    Pages
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Pages</h1>
            <div class="section-header-breadcrumb">
                @can('create-page')
                    <a href="{{ route('pages.create')}}" class="btn btn-primary form-btn">Page <i
                            class="fas fa-plus"></i></a>
                @endcan
            </div>
        </div>
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    @include('pages.table')
                </div>
            </div>
        </div>

        {{--        @include('stisla-templates::common.paginate', ['records' => $pages])--}}

    </section>
@endsection

resources/views/pages/table.blade.php
<link href="{{ asset('/assets/css/jquery.dataTables.min.css') }}" rel="stylesheet">

<div class="table-responsive">
    <table class="table table-bordered" id="pages-table">
        <thead>
        <tr>
            <th class="text-center">Name</th>
            <th class="text-center">Route</th>
            <th class="text-center">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($pages as $page)
            <tr>
                <td class="text-center">{{ $page->getName() }}</td>
                <td class="text-center">{{ $page->getRoute() }}</td>
                <td class="text-center">
                    {!! Form::open(['route' => ['pages.destroy', $page->get('id')], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @can('read-page')
                            <a href="{!! route('pages.show', [$page->get('id')]) !!}" target="_blank" class='btn btn-light action-btn '><i
                                    class="fa fa-eye"></i></a>
                        @endcan
                        @can('update-page')
                            <a href="{!! route('pages.setting', ['id'=>$page->get('id')]) !!}"
                               class='btn btn-info action-btn edit-btn'><i class="fas fa-cog"></i></a>
                        @endcan
                        @can('update-page')
                            <a href="{!! route('pages.edit', [$page->get('id')]) !!}"
                               class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                        @endcan
                        @can('delete-page')
                            {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("Are you sure want to delete this record ?")']) !!}
                        @endcan
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

<script src="{{ asset('/assets/js/jquery.min.js') }}"></script>
<script src="{{ asset('/assets/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/assets/js/jquery.nicescroll.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/select2.min.js') }}"></script>

<script>
    $(document).ready(function () {
        $.noConflict();
        $('#pages-table').DataTable();
    });
</script>